# h*luv_to_hex
#    ^ h*luv_to_rgb -> rgb_to_hex
#          ^ h*luv_to_lch -> lch_to_rgb
#                                ^ lch_to_luv -> luv_to_xyz -> xyz_to_rgb
def hsluv_to_hex(_hx_tuple: tuple[float, float, float]) -> str: ...
def hpluv_to_hex(_hx_tuple: tuple[float, float, float]) -> str: ...
def hsluv_to_rgb(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hpluv_to_rgb(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hsluv_to_lch(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hpluv_to_lch(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def lch_to_rgb(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def lch_to_luv(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def luv_to_xyz(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def xyz_to_rgb(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def rgb_to_hex(_hx_tuple: tuple[float, float, float]) -> str: ...

# hex_to_h*luv
#     ^ hex_to_rgb -> rgb_to_h*luv
#                         ^ rgb_to_lch -> lch_to_h*luv
#                               ^ rgb_to_xyz -> xyz_to_luv -> luv_to_lch
def hex_to_hsluv(s: str) -> tuple[float, float, float]: ...
def hex_to_hpluv(s: str) -> tuple[float, float, float]: ...
def hex_to_rgb(_hex: str) -> tuple[float, float, float]: ...
def rgb_to_hsluv(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def rgb_to_hpluv(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def rgb_to_lch(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def rgb_to_xyz(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def xyz_to_luv(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def luv_to_lch(_hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def lch_to_hsluv(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def lch_to_hpluv(
    _hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
