# h*luv_to_hex
#    ^ h*luv_to_rgb -> rgb_to_hex
#          ^ h*luv_to_lch -> lch_to_rgb
#                                ^ lch_to_luv -> luv_to_xyz -> xyz_to_rgb
def hsluv_to_hex(hx_tuple: tuple[float, float, float]) -> str: ...
def hpluv_to_hex(hx_tuple: tuple[float, float, float]) -> str: ...
def hsluv_to_rgb(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hpluv_to_rgb(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hsluv_to_lch(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def hpluv_to_lch(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def lch_to_rgb(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def lch_to_luv(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def luv_to_xyz(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def xyz_to_rgb(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def rgb_to_hex(hx_tuple: tuple[float, float, float]) -> str: ...

# hex_to_h*luv
#     ^ hex_to_rgb -> rgb_to_h*luv
#                         ^ rgb_to_lch -> lch_to_h*luv
#                               ^ rgb_to_xyz -> xyz_to_luv -> luv_to_lch
def hex_to_hsluv(rgb_hex: str) -> tuple[float, float, float]: ...
def hex_to_hpluv(rgb_hex: str) -> tuple[float, float, float]: ...
def hex_to_rgb(rgb_hex: str) -> tuple[float, float, float]: ...
def rgb_to_hsluv(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def rgb_to_hpluv(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def rgb_to_lch(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def rgb_to_xyz(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def xyz_to_luv(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def luv_to_lch(hx_tuple: tuple[float, float, float]) -> tuple[float, float, float]: ...
def lch_to_hsluv(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
def lch_to_hpluv(
    hx_tuple: tuple[float, float, float],
) -> tuple[float, float, float]: ...
